CREATE TABLE IF NOT EXISTS `alert_silences` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `rule_id` BIGINT NOT NULL DEFAULT 0,
  `agent_id` VARCHAR(100) NOT NULL DEFAULT '',
  `service_tree_id` BIGINT NOT NULL DEFAULT 0,
  `owner_id` BIGINT NOT NULL DEFAULT 0,
  `reason` VARCHAR(500) NOT NULL DEFAULT '',
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `starts_at` DATETIME NOT NULL,
  `ends_at` DATETIME NOT NULL,
  `created_by` BIGINT NOT NULL DEFAULT 0,
  `updated_by` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_alert_silences_name` (`name`),
  KEY `idx_alert_silences_rule_id` (`rule_id`),
  KEY `idx_alert_silences_agent_id` (`agent_id`),
  KEY `idx_alert_silences_service_tree_id` (`service_tree_id`),
  KEY `idx_alert_silences_owner_id` (`owner_id`),
  KEY `idx_alert_silences_enabled` (`enabled`),
  KEY `idx_alert_silences_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `oncall_schedules` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `description` VARCHAR(500) NOT NULL DEFAULT '',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  `users_json` JSON NOT NULL,
  `rotation_days` INT NOT NULL DEFAULT 1,
  `notify_channels_json` JSON NOT NULL,
  `escalation_minutes` INT NOT NULL DEFAULT 0,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `created_by` BIGINT NOT NULL DEFAULT 0,
  `updated_by` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_oncall_schedules_name` (`name`),
  KEY `idx_oncall_schedules_enabled` (`enabled`),
  KEY `idx_oncall_schedules_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
